# -*- coding: utf-8 -*-
"""PYTorch

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iuXt9IXVeafxHJzHOin2p30ihxuI0REa
"""

import torch

x = torch.tensor([5, 3])
y = torch.tensor([2, 1])

print(x*y)

x = torch.zeros(2,4)
x

x.shape

y = torch.rand([2, 5])
y

